name: Laravel CI/CD Pipeline

# Trigger the workflow on push to main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Use the PHP version your Laravel project requires
          extensions: mbstring, dom, fileinfo, mysql, sqlite, curl # Add required extensions
          coverage: pcov # Optional: For code coverage

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Install NPM dependencies (if using Laravel Mix or Vite)
      - name: Install NPM dependencies
        run: npm install

      # Build assets (if using Laravel Mix or Vite)
      - name: Build assets
        run: npm run build

      # Run migrations and seeders (optional)
      #- name: Run migrations
      #  run: php artisan migrate --force

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "Deploying to production..."
        # Add deployment commands here (e.g., SSH into server, deploy scripts, etc.)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: http://175.142.232.32/
          username: "itsaie"
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNs8QWYoVkO9G8PRlWZSECebELou9h6/EcyMD3YkspWC2AdwqRQluALKXYXJ6Fs9QeNmwARqkrsW9JJWCsls/wR2go8+FMwgrm9dWyAxNmtibpW10Pk7GQ4+tv8AODUq2g4dd8dQc42ic1FOC4bP+F4LrlpEfo8EAwNurDjhhkpjsP1XMZEYw6n/AMn1U/RczrR+hU46f/ZmeVYNBEaTTzZT+c3td3UY2VbICpEIvkQkI74pXv6jIUSvC73wC7oCjRIocnjct6yZ+i2uZjsdgMHPxB9JeYBzZoCs/TA7mS1wb3XE6/NhSo7e+aE8mL2naSRSryRO5ar+gl1iAc2j9oBIzEJPdh3cHbS62zhf/wjCufoDosIBCxCihCr8wiCZvooAqOt2qbJ4IZPZ1k8tyws4dFJGywTFfJ7y9YKkRQu1cW4C4eDpWAvS5LCJZeAqNVx0cqI6Ti1CyN1ZQS8ij9VwN+RU4OmJsxI0U+QUXfpQ5o84M+1pcC0Xu+Ht0w23ZDI5AGv+DkTZnrTPNuDWt5CIz/wqzIX59CedQpintOs+4GkCYzLPLJzIFGK0JNlLMh++QHafhXFz0wzwM89T1hVyrg46YsCYfgdBYDiGUMW0ENRt7dwv7LIcpPqxpnAJAL8I5ARsk5sF/pjB5GsuWzc3f0Iw7tRK2wzgilI7ATZQ== hazreemahmood@gmail.com"
          script: |
            cd /var/www/my-laravel-app
            git pull origin main
            composer install --optimize-autoloader --no-dev
            php artisan optimize:clear
            php artisan optimize
