name: Laravel CI/CD Pipeline

# Trigger the workflow on push to main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Use the PHP version your Laravel project requires
          extensions: mbstring, dom, fileinfo, mysql, sqlite, curl # Add required extensions
          coverage: pcov # Optional: For code coverage

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Install NPM dependencies (if using Laravel Mix or Vite)
      - name: Install NPM dependencies
        run: npm install

      # Build assets (if using Laravel Mix or Vite)
      - name: Build assets
        run: npm run build

      # Run migrations and seeders (optional)
      #- name: Run migrations
      #  run: php artisan migrate --force

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "hazreemahmood@github.com"
          git config --global user.name "Hazree Mahmood"
        # Add deployment commands here (e.g., SSH into server, deploy scripts, etc.)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 2222
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: 12345
          script: |
            cd /var/www/html/my-laravel-app
            git pull
            php artisan optimize:clear
